### ISSUE TITLE
Change username does not work

### ISSUE THREAD

**Issue by cr04ch** [the-linux-schools-project/karoshi-server#17]
After I install the 171210-0902 patch, to change the username does not work (I tried it as admin).

In the log I see this: `change_username - No MD5Checksum`.

I think the reason is that the script `change_username.cgi` is missing from the `tech` directory (`setup_web_controls` does not copy because this line is no longer included), so the md5sum is missing too, and the script is exited with error.

**Comment by mpsharrad** [comment]
Hi thanks for the info.

I made a change so that change username and change primary group are all on
the edit user page which is why I deleted change _username.cgi.

How did you get to that page - did I leave something in the menu?

**Comment by cr04ch** [comment]
I select `Users and Groups -> Edit User` from the menu, so I get `/cgi-bin/admin/show_user_info_fm.cgi`.
Then I select a user and click `Show user info` button, and I see the form that show all changable user data, included username and primary group too. The location is `/cgi-bin/admin/show_user_info.cgi`.

Thist script invoke `/opt/karoshi/web_controls/exec/show_user_info`, wich script generate the form. The Submit button invoke `/cgi-bin/admin/change_user_info.cgi`, this script invoke `/opt/karoshi/web_controls/exec/change_user_info`, and this script invoke `/opt/karoshi/web_controls/exec/change_username` if username is changed (if I understand).

This last script verify `/opt/karoshi/web_controls/checksums/tech_checksums/change_username_cgi` and exits if the file does not exist.

**Comment by cr04ch** [comment]
Works fine after I install the 171212-2016. Thanks!
